### ISSUE TITLE
Minor mismatch between AssemblyScript and C 

### ISSUE THREAD

**Issue by MaxGraey** [micheleriva/c-vs-ts-wasm#1]
Hi, glad to see someone try compare how different compilers produce wasm's binary.
But I should be mentioned in AS version you use `number` type which just alias of `f64` instead `int32` as in C version. So AS version should looks like:
```ts
function fibonacci(i: i32): i32 { // or i64
  if (i < 0) return -1
  else if (i == 0) return 0
  else if (i == 1) return 1
  else return fibonacci(i - 1) + fibonacci(i - 2)
}
```
Another issue is AS doesn't use optimization at all in your build command. So much better is:
```
"asbuild": "asc src/ts/main.ts -b src/ts/a.out.wasm -t src/ts/a.out.wat --validate --measure -O3"
```

Thanks!

**Comment by micheleriva** [comment]
Hi @MaxGraey,
you are totally right! I'm going to update it asap! :)

**Comment by micheleriva** [comment]
Hi @MaxGraey,
I've updated the codebase. Thank you so much again!
